### ISSUE TITLE
Players with "Mute on start" unchecked start muted.

### ISSUE THREAD

**Issue by bneilon** [jwplayer/jw-showcase#113] opened 2017-04-06 20:48 UTC
### Expected Behavior

Players with "Mute on start" UNchecked start UNmuted.

### Actual Behavior

In certain situations, players with "Mute on start" unchecked start muted.

### Steps to reproduce

Names of attached screenshots correspond to these steps
Start: https://www.fastcompany.com/videos/list/jVdHZUiT/video/4MTGSdXQ/taste-teaches-us-an-important-lesson-in-american-history
Step 1a: Play & unmute the video (if muted)
Step 1b: Click the “Fast Company” logo to go to the homepage
Step 2a: Scroll down to the video module
Step 2b: Allow the player to begin playing editorial content (I usually skip the ad, if there is one.  The seems to have no effect)
Step 2c: Click “Video” to return to the showcase area.
Step 3a: Click the video most recently played (or any other, I believe)
Step 4: video is muted again

![step 1](https://cloud.githubusercontent.com/assets/26070171/24774444/e5a02c22-1ae6-11e7-90e5-3b20f96c2e4a.png)
![step 2](https://cloud.githubusercontent.com/assets/26070171/24774442/e59d720c-1ae6-11e7-916d-37c75de73048.png)
![step 3](https://cloud.githubusercontent.com/assets/26070171/24774445/e5a15a7a-1ae6-11e7-94cc-5d31a61b2a86.png)
![step 4](https://cloud.githubusercontent.com/assets/26070171/24774443/e59f6b5c-1ae6-11e7-8914-870231c728a9.png)

### Environment

- Mac Pro 3.5 GHz 6-Core Intel Xeon E5, 
- OS X 10.9.5
- User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
- JW Showcase v3.1.0 | https://www.fastcompany.com/videos/

----------------------------------------------------------------------------------------

This template is provided as a guide to filing bugs and feature requests. Please replace 
all text *in italics* with details describing your issue. When submitting a feature request, 
"Steps to reproduce" can be substituted with a user story or list of acceptance criteria.

**Comment by johnluther** [comment] 2017-04-07 15:17
@HeidiW from JW Support as FYI

Thanks for the detailed report, @bneilon .

The developer assigned to this is out sick today, so we will have a more complete analysis early next week.

@ChristiaanScheermeijer,  here is some basic info I was able to gather:

- There are two different JW players in use on the site (homepage player is ID 76APbejE, Showcase is gHCndHf0).
- I was able to reproduce the muted playback on Showcase, but it only happens after visiting the homepage player, which is mute:true, I assume because it autoplays on scrollover.
- If I leave the homepage player **muted**, audio is **muted** on Showcase.
- If I manually **unmute** the homepage player, audio is **unmuted** on Showcase.

I think the cause is the jwplayer.mute cookie flag. Even though the player setup on Showcase is "mute:false," when the homepage player sets jwplayer.mute cookie to "true," that setting overrides the setup.

**Comment by ChristiaanScheermeijer** [comment] 2017-04-10 09:09
@johnluther I think you are right. In the Showcase player we don't explicitly set `mute: false` and I assume we don't want to overrule the `jwplayer.mute` cookie.

I'm not 100% sure, but the player should not set the `jwplayer.mute` cookie when using `mute: true`. Right @HeidiW?

**Comment by johnluther** [comment] 2017-04-11 13:42
@ChristiaanScheermeijer I am debating that behavior right now with the Player team, will keep this thread updated. :-)

**Comment by ChristiaanScheermeijer** [comment] 2017-05-01 14:54
@johnluther do you have a status update?

**Comment by johnluther** [comment] 2017-05-01 15:05
I talked about it with the team and they said the player is functioning as designed. 

Technically this is not an autoplay use case, since Fast Company is firing a "play" event on the homepage player when the user scrolls over the player.

**Closed** 2017-06-07 14:58 UTC
Labels: bug
